In [3]:
from knn import *
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
print(iris)
X = iris.data[:, :4] # for now, use the first two features.
y = iris.target
x1_min, x1_max = X[:, 2].min() - .5, X[:, 2].max() + .5
x2_min, x2_max = X[:, 3].min() - .5, X[:, 3].max() + .5
plt.figure(figsize=(8, 6))
# Plot the training points
plt.scatter(X[:, 2], X[:, 3], c=y, cmap=plt.cm.Set1,
 edgecolor='k')
plt.xlabel('Sepal length')
plt.ylabel('Sepal width')
plt.xlim(x1_min, x1_max)
plt.ylim(x2_min, x2_max)
plt.show()

ModuleNotFoundError: No module named 'knn'

In [4]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
train_data = []
train_target = []
test_data = []
test_target = []
i = 0
for i in range(len(iris.data)):
    if i%15 == 0:
        test_data.append(iris.data[i])
        test_target.append(iris.target[i])
    else:
        train_data.append(iris.data[i])
        train_target.append(iris.target[i])

In [6]:
test_data
    


[array([5.1, 3.5, 1.4, 0.2]),
 array([5.7, 4.4, 1.5, 0.4]),
 array([4.8, 3.1, 1.6, 0.2]),
 array([4.8, 3. , 1.4, 0.3]),
 array([5. , 2. , 3.5, 1. ]),
 array([6.6, 3. , 4.4, 1.4]),
 array([5.5, 2.6, 4.4, 1.2]),
 array([7.6, 3. , 6.6, 2.1]),
 array([6.9, 3.2, 5.7, 2.3]),
 array([7.7, 3. , 6.1, 2.3])]

In [7]:
def KNN1(data1,k):
    #for data in data1:
        #x_1 = data[0]
        #print(np.square(x_1))
        #for a in train_data:
        #    print(min(a))
            #print(f"{np.root(np.square(x_1 -a[0]))}asdasd")
            #distance.append(np.roots(np.square(x_1 - a[0])+np.square(x_2 - a[1])))
        
        print("asdasdasd")
        print(min(data1[0]))
        #for a in train_data:
            #print(round(x_1-a[0],1))
        print(k)
    #print(f"{data}\n")
KNN1(test_data,3)

asdasdasd
0.2
3


In [8]:
def KNN(data1, k):
    target = []
    
    for data in data1:
        x_1 = data[0]
        x_2 = data[1]
        find_label = []
        distance = []
        tar = []
        train_data1 = train_data.copy()
        train_target1 = train_target.copy()
        for a in train_data1:
            distance.append(np.sqrt(np.square(x_1 - a[0])+np.square(x_2 - a[1])))
        for a in range(k):
            distance_min = min(distance)
            for b in range(len(distance)):
                if distance_min == distance[b]:
                    del distance[b]
                    find_label.append(train_target1[b])
                    del train_target1[b]
                    del train_data1[b]
                    break
        c =[]
        for a in range(len(find_label)):
            c.append(find_label.count(find_label[a]))
            
        c_max = max(c)
        for i in range(len(c)):
            if c[i] == c_max:
                target.append(find_label[i])
                break
    return target
        
       

In [23]:
print(test_target)
print(test_data)
a = knn()
for i in range(10):
    print(a.KNN_obtain(test_data,i+1,train_data,train_target))



[0, 0, 0, 0, 1, 1, 1, 2, 2, 2]
[array([5.1, 3.5, 1.4, 0.2]), array([5.7, 4.4, 1.5, 0.4]), array([4.8, 3.1, 1.6, 0.2]), array([4.8, 3. , 1.4, 0.3]), array([5. , 2. , 3.5, 1. ]), array([6.6, 3. , 4.4, 1.4]), array([5.5, 2.6, 4.4, 1.2]), array([7.6, 3. , 6.6, 2.1]), array([6.9, 3.2, 5.7, 2.3]), array([7.7, 3. , 6.1, 2.3])]


NameError: name 'knn' is not defined